<?xml version="1.0"?><package format="3"><name>ad_pipeline</name><version>0.1.0</version><description>Launch files for the mini stack.</description><maintainer email="developer@example.com">developer</maintainer><license>Apache-2.0</license><buildtool_depend>ament_python</buildtool_depend><exec_depend>launch</exec_depend><exec_depend>launch_ros</exec_depend><exec_depend>ad_gazebo_sim</exec_depend><exec_depend>ad_localization</exec_depend><exec_depend>ad_perception</exec_depend><exec_depend>ad_behavior</exec_depend><exec_depend>ad_planning_control</exec_depend><export><build_type>ament_python</build_type></export></package>
